stages:
  - Build
  - Package

before_script:
  - export BASE_URL=${BASE_URL:-$(echo $CI_PROJECT_URL |  cut -d'/' -f1-3)}
  - export CI_COMMIT_SHA_SHORT=$(echo ${CI_COMMIT_SHA} | cut -c -8)
  - >
    if [ -z "$CROSS_CLOUD_YML" ] && [ -z "$DASHBOARD_API_HOST_PORT" ]; then
       export CROSS_CLOUD_YML="https://raw.githubusercontent.com/CrossCloudCI/cncf-configuration/master/cross-cloud.yml"
       export DASHBOARD_API_HOST_PORT="devapi.cncf.ci"
    fi
  - >
    if ruby -v ; then
        echo 'Ruby found, not using rvm'
        cp -a /opt/local/dashboard /dashboard 
        pushd /dashboard
        source /opt/local/.env
        bundle install
        ./bin/update_dashboard
        popd
    else
       source /opt/local/etc/rvmrc
       source /opt/local/etc/profile.d/rvm.sh
       cp -a /opt/local/dashboard /dashboard
       pushd /dashboard
       source /opt/local/.env
       ./bin/update_dashboard
       popd
    fi

compile:
  stage: Build
  image: "crosscloudci/debian-ruby-docker"
  script:
    - >
      if [ "$BASE_URL" == "https://gitlab.cncf.ci" ]; then
        echo curl -f -X GET "https://productionapi.cncf.ci/ciproxy/v1/ci_status_build/commit_ref?project=${CI_PROJECT_NAME}&ref=${CI_COMMIT_SHA}&arch=$ARCH"
        curl -f -X GET "https://productionapi.cncf.ci/ciproxy/v1/ci_status_build/commit_ref?project=${CI_PROJECT_NAME}&ref=${CI_COMMIT_SHA}&arch=$ARCH" 

      elif [ "$BASE_URL" == "https://gitlab.staging.cncf.ci" ]; then
        echo curl -f -X GET "https://stagingapi.cncf.ci/ciproxy/v1/ci_status_build/commit_ref?project=${CI_PROJECT_NAME}&ref=${CI_COMMIT_SHA}&arch=$ARCH"
        curl -f -X GET "https://stagingapi.cncf.ci/ciproxy/v1/ci_status_build/commit_ref?project=${CI_PROJECT_NAME}&ref=${CI_COMMIT_SHA}&arch=$ARCH" 

      elif [ "$BASE_URL" == "https://gitlab.cidev.cncf.ci" ]; then
        echo curl -f -X GET "https://devapi.cncf.ci/ciproxy/v1/ci_status_build/commit_ref?project=${CI_PROJECT_NAME}&ref=${CI_COMMIT_SHA}&arch=$ARCH"
        curl -f -X GET "https://devapi.cncf.ci/ciproxy/v1/ci_status_build/commit_ref?project=${CI_PROJECT_NAME}&ref=${CI_COMMIT_SHA}&arch=$ARCH" 

      else
        echo curl -f -X GET "https://devapi.cncf.ci/ciproxy/v1/ci_status_build/commit_ref?project=${CI_PROJECT_NAME}&ref=${CI_COMMIT_SHA}&arch=$ARCH"
        curl -f -X GET "https://devapi.cncf.ci/ciproxy/v1/ci_status_build/commit_ref?project=${CI_PROJECT_NAME}&ref=${CI_COMMIT_SHA}&arch=$ARCH" 

      fi

container:
  stage: Package
  image: crosscloudci/debian-docker
  script:
    - echo 'Dummy Job'
